### ISSUE TITLE
Crash app on IOS 10.x when press save button

### ISSUE THREAD

**Issue by d2luu** [prscX/react-native-photo-editor#14]
@prscX Thank for really good library.
But my app was crashed when saving the image on IOS 10.x, other versions of IOS still be OK.
Besides, edit buttons on head overlap the status bar on any iPhone run on ios version <=10.x
<img width="400" alt="screen shot 2018-10-10 at 4 43 20 pm" src="https://user-images.githubusercontent.com/14581772/46720623-12674880-ccac-11e8-9702-5221b67d265e.png">

**Comment by prscX** [comment]
Thanks @d2luu for raising the issue.

* **Layout**: I believe the layout issue is fixed in the latest version. Can you please verify the same.
* **Save Issue**: Can you please share the error call stack. It is difficult to visualize the issues. However have you followed below installation step defined in `README`:

Add below property to your info.list

```
	<key>NSPhotoLibraryAddUsageDescription</key>
	<string>Application needs permission to write photos...</string>
```

Thanks
</ Pranav >

**Comment by d2luu** [comment]
@prscX thanks for your response. 
 * **Layout issue**: Currently, I use react-native-photo-editor version 0.0.5 (latest version). But the layout issue still exists. As you can see the picture below, on the left is iPhone run on ios 11.1 and on the right is 10.1.
<img width="954" alt="ios 10 vs 11" src="https://user-images.githubusercontent.com/14581772/46936731-4a023600-d09a-11e8-8b3b-3dd0a778a469.png">

* **Save issue**: On the iPhone run on IOS 10.x, when I save image, Xcode step to debug mode like this: 
<img width="1440" alt="screen shot 2018-10-15 at 4 35 31 pm" src="https://user-images.githubusercontent.com/14581772/46937520-77e87a00-d09c-11e8-85d9-0241184cf434.png">
I try to press Step Over on Xcode, the app was crashed.

I installed properly like doc and **save issue** only happened on IOS 10.x version, other version still be ok.

**Comment by d2luu** [comment]
@prscX here is stack trace on Xcode:
<img width="917" alt="screen shot 2018-11-05 at 5 26 53 pm" src="https://user-images.githubusercontent.com/14581772/47986445-20c84900-e120-11e8-9caa-5d108560a393.png">
It only happen in ios 10 although my Info.plist had NSPhotoLibraryUsageDescription.

**Comment by d2luu** [comment]
And other question, is this library only work on android with API > 27?
I have a Samsung galaxy note FE, with Android 8.0 but photo editor not work.

**Comment by d2luu** [comment]
@prscX  
I found why the image can't save on ios 10. It's because ios 10 need NSPhotoLibraryUsageDescription, not ~~NSPhotoLibraryAddUsageDescription~~. So in order to save image on ios 10, must add below properties on Info.plist:
```xml
<key>NSPhotoLibraryUsageDescription</key>
<string>IOS 10 needs permission to write photos...</string>

<key>NSPhotoLibraryAddUsageDescription</key>
<string>Application needs permission to write photos...</string>
```

**But *layout issue* still exist on ios <= 10**

**Comment by prscX** [comment]
Thanks @d2luu for sharing the solution. Can you please share PR of the same.

Thanks
</ Pranav >
